/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.collect.Range;
import com.google.common.collect.RangeSet;
import com.google.common.collect.TreeRangeSet;

public class HelloOtus {
    public static void main(String[] args) {
        RangeSet<Integer> rangeSet = TreeRangeSet.create();
        rangeSet.add(Range.closed(1, 10));
        rangeSet.add(Range.closedOpen(11, 15));
        rangeSet.add(Range.open(15, 20));
        System.out.println("rangeSet: " + rangeSet);
        System.out.println("rangeSet.span(): " + rangeSet.span());
    }
}
